UN-OCHA/hid-api

api/controllers/UserController.js
This allows the Snap Service usage report to label HID calls properly.
I *think* I'm passing the correct `req.headers[]` but please do double check, as JS is not my forté.
=> [HID-1790] Set a service on Snap calls, also pass User-Agent and remote IP.

emails/forced_password_reset/fr/html.ejs, emails/forced_password_reset/html.ejs, emails/forced_password_reset_alert/fr/html.ejs, emails/forced_password_reset_alert/html.ejs, emails/forced_password_reset_alert7/fr/html.ejs, emails/forced_password_reset_alert7/html.ejs
Changes to the email notification templates. I noticed that there were trivial differences between the templates and opted to make them all conform to one convention.
* The first long paragraph had a line-break in french, but not in the new text I was supplied in English. I turned it into one paragraph
* The links present in the English were not in the templates for French. I've added them to French. I don't speak French so please make sure the text inside the links is coherent.
=> HID-1807: update wording of reset notifications

package.json
Blocks https://github.com/UN-OCHA/hid_app2/pull/147
Without this update, the client-side library can validate but then the visitor is shown an error when clicking the <kbd>+</kbd> button.
=> HID-1817: update libphonenumber

api/services/HelperService.js
Adding some authorized domains for CD QA plus local testing.
* The app.cd domain is for our CD QA environment
* The app.hid.vm are for localtesting. Non-HTTPS is included to facilitate cross-browser testing via BrowserStack
=> HID-1838: add more authorized domains for development/testing

templates/header.ejs
OCHA Services menu needs to function normally even on HID Auth screen.
Since there's no pre-existing JS tools/framework on the HID Auth page, I had to replicate a couple features and rewrite some vanilla JS by hand, but it's all pretty tidy and contained to the header template. It also keeps the page lightweight to avoid adding all those tools in the mix.
=> HID-1878: OCHA Services dropdown

api/services/HelperService.js
We were unable to register or reset passwords as Auth users on dev. I added the domain and reorganized the list to better label all the domains we have in there.
=> HID-1890: add auth.dev to authorizedDomains allowlist

api/controllers/UserController.js
Followup to #67 — making the log message more descriptive when a domain is not in the allowlist.
=> HID-1890: more descriptive log for authorizedDomain allowlist

templates/header.ejs
The CD Header column headings and "See All" button were distorted in Edge.
I was using `window.CSS.supports('display: grid')` and Edge 18 didn't seem to like that syntax. Switching to `window.CSS.supports('display', 'grid')` cleared it up without regressions in other browsers.
=> HID-1878: use Edge-compatible window.CSS.supports query

templates/header.ejs
Installs GA tracking for OCHA Services menu. The [docs say that immediate use is possible](https://developers.google.com/analytics/devguides/collection/analyticsjs/command-queue-reference#ready-callback) after the instantiation in the `<head>` and that any uses of `ga()` prior to its ready callback will be queued up and emitted after it instantiates.
=> HID-1878: track usage of OCHA Services menu in GA

docker-compose.yml
Only for the target branch!
Not needed elsewhere.
Fixes this errors in the hpc dev setup script:
```
Recreating 96357ceb011b_hid_api_db_1 ... error
ERROR: for 96357ceb011b_hid_api_db_1  Cannot start service db: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/Users/serban/Projects/OCHA/HPC/hid_api/db\\\" to rootfs \\\"/var/lib/docker/overlay2/8b9348a37094a2584ebf50039995a99cbfb574012cbeb5d539aafd97ac640ac1/merged\\\" at \\\"/var/lib/docker/overlay2/8b9348a37094a2584ebf50039995a99cbfb574012cbeb5d539aafd97ac640ac1/merged/srv/db\\\" caused \\\"mkdir /var/lib/docker/overlay2/8b9348a37094a2584ebf50039995a99cbfb574012cbeb5d539aafd97ac640ac1/merged/srv/db: permission …
```
=> [OPS-6231] minimal edits to make this docker-compose actually work

api/controllers/UserController.js
While working on HID-2002 I noticed it is possible to craft an API request that "changes" your new password to the current password. All copy on our site/api-docs implies this is not possible. Small conditional is all we needed.
=> HID-1967: enforce policy that new password cannot match old password

api/controllers/TOTPController.js
As simple as expected :) We should offer clients the ability to print the config and allow a user to copy/paste. There is no change to our security by offering this option, since QR codes are also plaintext (in a manner of speaking).
Obviously this PR might bring to attention the poor naming convention currently used by the API, but for backwards-compat I don't want to change the existing property name without exposing a V3 route that declares the breaking change.
If we did offer a V3, I'd probably reshape the object to be:
```js
{
url: otpauthUrl,
qrcode: qrcode,
}
```
=> HID-2008: include plaintext URL when sending TOTP config

package-lock.json, package.json
I updated a lot of stuff, got rid of other things that are totally unused, and updated some other meta data. According to `npm audit` we went from 131-odd vulns to just one low severity issue, and I ticketed the work since it requires some non-trivial breaking changes (HID-2024).
I also specified a couple peer dependencies to make npm shut up about it.
You'll notice I went _backwards_ with the npm version, and unfortunately that's necessary to match what our container has. We will have a node 12 upgrade on the horizon and we can upgrade at that time.
=> OPS-6350: big ol' dependency update

.travis.yml, api/services/EmailService.js, commands/decommissionEmailsAuth.js, commands/decommissionEmailsProfile.js, emails/decommission_auth/fr/html.ejs, emails/decommission_auth/fr/subject.ejs, emails/decommission_auth/html.ejs, emails/decommission_auth/subject.ejs, emails/decommission_profile/fr/html.ejs, emails/decommission_profile/fr/subject.ejs, emails/decommission_profile/html.ejs, emails/decommission_profile/subject.ejs, package-lock.json, package.json
Two new emails to notify users about HID v2 decommissioning. There are separate emails for profile and auth users.
Bonus perk of @orakili reviewing is he can spot all the french typos I probably made 😆 
Email subject lines for both EN/FR pending
=> HID-2021 / HID-2022: emails to notify auth/profile users about decommissioning

api/models/User.js
We couldn't upload photos on AWS domains. This band-aids a fix.
Updated the list of TODOs in HID-1894 to include this list.
=> HID-2035: allow picture uploads to AWS/local environments

api/controllers/UserController.js, config/routes.js
Following up on #86 and UN-OCHA/hid_app2#209
This branch removes any user's ability to reset passwords using generic `PUT`s to the API. In previous PRs we agreed that the work to adopt v3 password complexity requirements was unfinished; I believe this PR addresses all previous issues.
What remains in the API is the `/user/:id/password` for both v2/v3. Every time the strength check is invoked, it is done so by first looking whether v2 or v3 was called, and it checks strength based on that. When we deprecate/remove v2, we can simplify all of this, but for now it meets our goals without disrupting existing functionality.
Although this is technically a breaking change, the only client of concern is the AngularJS codebase, which I already patched up and deployed to dev:
- AngularJS app is …
=> HID-1967: update password strength checks

api/controllers/UserController.js, config/routes.js
I uncovered this while doing something else but it's worth tending to. This allows us to fix up yet another instance of our clients using generic `PUT`s to do destructive operations.
The substantive change is the addition of parameter validation. The method could not function before, because the parameter was named but not validated.
=> HID-2038: remove emails using dedicated method

commands/decommissionEmailsAuth.js
To enable QA, I added a new `locale` argument to our Jenkins job. This PR allows us to use it on Jenkins.
Note: the corresponding prod job does NOT have such an argument so I checked on my local (and will try again in Jenkins on dev) that omitting the arg has the intended effect.
=> HID-2022: frenchity-french emails cannot be frenchity found

config/env/local.js
PR smaller than I expected. I always see an error in my console when booting and thought it must apply to all environments, but it ended up being local only.
```
api_1  | (node:454) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
```
Anyway, it's fixed.
=> HID-2026: apply standard settings to local environment

api/controllers/AuthController.js
Log errors to ELK during any operation related to OAuth. We have occasionally had 500s but nothing shows up in ELK from the API itself. This will give us something to go on when people report problems.
=> HID-2054: catch all errors and log stack trace to ELK

api/controllers/AuthController.js, docs/v3/hid.yml, docs/v3/swaggerBase.yaml, package-lock.json, package.json
This is the beginning of our effort to maintain API docs for v3. I only documented one method, but it was enough to learn the following about Swagger and the specific tool, `swagger-inline`, that I picked to use going forward:
- Docs can now be placed above each method they describe. I find this far more logical than having them separated in a gigantic YML file in a far-away directory.
- The "base" file is located at `docs/v3/swaggerBase.yaml` and it holds everything not specific to an individual route: Swagger version, API URLs, tags, reusable schemas, etc.
- `docker-compose exec dev npm run docs` will compile the docs to `docs/v3/hid.yml`
- There's an online editor which validates the output YML: https://editor.swagger.io/
Someday I'd love to get the validation running as the docs are …
=> HID-2052: Swagger inline

api/controllers/AuthController.js, api/controllers/ServiceController.js
My guess is that a previous version of `hapi` used this syntax, and the couple code paths I found are just never used. I know the `signRequest` route is internal to HID so that's why we never see problems from it.
Anyway, they're all squared and throwing normal errors like the rest of the codebase.
=> HID-2063: remove direct calls to reply()

config/env/local.js, config/env/production.js, config/env/staging.js, config/env/testing.js
Deprecation warning I see every time the app restarts. The "Server Discovery and Monitoring engine" has been deprecated and will eventually be removed. We can use the new one by supplying a boolean.
There doesn't seem to be any other side effects aside from removing the warning.
=> HID-2048: useUnifiedTopology in mongoose config

api/policies/AuthPolicy.js
Our authentication/authorization policy to check if someone only had one possible rejection outcome: HTTP 403. We send 403 even if someone forgets credentials entirely.
[MDN says that 403 represents a rejection based on application logic](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403), and re-authenticating will have no effect. So we should not be sending 403s to people that forgot credentials. 401 is consistent with the rest of the app.
This PR adds a 401 response when credentials are missing, and continues returning 403 when the user authenticated properly, but does not have admin permissions.
One other thing: I wrapped the successful `return` statement in an explicit conditional because I feel like something as important as admin perms should not be implicitly allowed to …
=> HID-2078: AuthPolicy.isAdmin can return both 401/403

api/controllers/ClientController.js, docs/v3/hid.yml
The operation to delete an OAuth client returned 204 no matter what happened inside the function. That meant successive calls to `DELETE /api/v3/client/{id}` would yield 204 every time. Now it does a lookup and 404s when nothing was found.
I updated the shared v2/v3 function but since this is an admin-only feature of HID, it's not bothering anyone to change behavior.
=> HID-2081: DELETE /client/{id} should 404 when client doesn't exist

api/controllers/TOTPController.js
We never supported SMS. This makes sense to remove. Found during #107
=> HID-2082: disallow SMS as TOTP method

api/controllers/UserController.js, api/policies/UserPolicy.js, docs/v3/hid.yml, docs/v3/swaggerBase.yaml
There was a comment in the API to not log an entire payload because the password was inside it. Far better to delete that property and send along any other info we have, since the event is logging a validation failure and people might want to debug or otherwise investigate.
While testing I found it in the security policy too.
I also found that I'd forgotten to document the `password` and `confirm_password` params in our new docs. Plus, I noticed that our v3 is also sending the wrong field (`password_confirm` instead of `confirm_password`) so that's a bug that might have otherwise sat for a while before being found.
=> HID-2093: log payload during failed user creation

api/controllers/UserController.js
PR should help illuminate future problems with DB queries when testing on dev/stage. We sometimes have problems with `NOTABLESCAN` causing this query to fail sometimes, so it's helpful to log even if only for our non-prod environments.
=> HID-2092: log errors when querying DB for email confirmation

emails/includes/footer_en.ejs, emails/includes/footer_fr.ejs
Small follow-up to remove social links from all email templates. They share common header/footer files so this will apply to any email we send.
=> HID-2088: remove links from all email footers

api/controllers/UserController.js, api/models/User.js, api/policies/UserPolicy.js, config/routes.js, templates/header.ejs
We had a 500 when trying to GET `/user` on both v2 and v3. I have fixed the bug in case we somehow allow unauthenticated requests in the future, and also applied a new security policy called `canFind` which explicitly disallows unauthenticated requests.
The `canFind` can safely block unauthenticated GETs to both v2 and v3 because before this PR, they weren't returning data anyway. So instead of 500 this will 401 the request.
=> HID-2077: prevent 500 during GET /user

docs/v3/hid.yml, docs/v3/swaggerBase.yaml
We told all the teams to stop using dev and yet our API docs point to dev by default.
=> Set stage as default origin for API docs

api/controllers/ServiceController.js, api/controllers/ViewController.js, api/models/User.js, api/services/GSSSyncService.js
- Making sure that all instances of `hid.error` are one type of value (string in this case)
- Moved any error objects to a new `err_object` field.
- Added some `security`/`fail` flags when appropriate
=> OPS-6862: ensure all error logs follow same conventions as info/warning

api/controllers/AuthController.js, config/routes.js, docs/v3/hid.yml, plugins/hapi-auth-hid/index.js
We want a convenience method to authorize admins only. Since all endpoints are already covered by various security policies this is truly a convenience method to allow our HID Admin tool to block non-admin logins with a clear 403 response.
=> HID-2104: create separate admin-only JWT auth endpoint

config/logs.js
The logging improvements from #128 were causing problems when sending requests with a Basic Auth header. Some cleanup and a few more filters to properly catch the Basic Auth header and also sanitize when found.
I am fairly certain the problem was introduced in 4ee6824 but since I ended up moving code between files I gave up when trying to bisect.
Setup the [Extra-secure authorization process](https://github.com/UN-OCHA/hid_api/wiki/Integrating-with-HID-via-OAuth#extra-secure-authentication-process) to test locally. If the initial request does not 500, then the test is successful.
We are also working on patching some dev sites to have a permanent test mechanism on dev. See HID-2110 and OPS-6839 for details.
=> HID-2110: fix fatal errors during OAuth logins

emails/admin_delete/fr/html.ejs, emails/admin_delete/html.ejs, emails/auth_to_profile/fr/html.ejs, emails/auth_to_profile/html.ejs, emails/forced_password_reset/fr/html.ejs, emails/forced_password_reset/html.ejs, emails/forced_password_reset_alert/fr/html.ejs, emails/forced_password_reset_alert/html.ejs, emails/forced_password_reset_alert7/fr/html.ejs, emails/forced_password_reset_alert7/html.ejs, templates/message.html
Updating where we send people when we mention HID. We now point back at Auth instead of the soon-to-be decommissioned HID Contacts app.
=> HID-2120: update URLs

templates/header.ejs
Update our CD Header to ensure that HID Auth points people back to itself if they somehow decide to click that link.
=> HID-2125: point to HID Auth in OCHA Services

api/controllers/AuthController.js, api/controllers/UserController.js, api/services/GSSSyncService.js, plugins/hapi-auth-hid/index.js
We had a couple issues reported in the ops ticket:
- `hid.user` had data of type `ObjectID` instead of strings sometimes
- `hid.error` had data of type `String` or sometimes `Error`  — but this seems to have been taken care of during 2020-09-30 deploy.
The PR has three fixes:
- attempts to get all the user ID stuff straightened out
- adds some additional attributes (email/ID) to a few logs
- fixes OAuth-authenticated requests to log the `client_id` inside `hid.oauth` instead of `hid.user`, and populated `hid.user` with correct data
Can be complicated, but what I do is use GHO to log in on my local HID API:
- Add a GHO OAuth client to your local HID using the config from within GHO local drupal container.
- As drupal admin, go to https://gho.test/admin/config/social-api/social-auth/hid
- …
=> OPS-6803: fix inconsistent log conventions

templates/settings.html
Branched from https://github.com/UN-OCHA/hid_api/pull/159
1. Currently placeholder markup only for both Password reset form, and 2FA tab
2. TOTP conditional based on vue app, but missing the "Activation Steps. TBD
=> HID-2126 Password reset form and 2FA activation

api/controllers/UserController.js, api/services/EmailService.js
We previously only logged our intention to send an email. Now we actually log the result of the promise's success or error. Helpful for the problem at hand?
=> OPS-7122: log result when trying to send emails

api/controllers/UserController.js, api/controllers/ViewController.js, api/models/User.js, templates/formassets.ejs, templates/login.html, templates/message.html, templates/new_password.html, templates/password.html, templates/register.html
Ok I admit this PR has scope creep, but it all had to do with password reset or registration.
- Rename `isStrongPasswordV3` to `isStrongPassword` and delete the old v2 version using that name
- Remove all the temporary business logic that checked the request URL to determine which to use
- Ensure adoption is working within HID Auth
- Frontend/text updates to HID Auth
- Used HTML5 form validation on `new_password` and `register` forms.
- Consolidated JS form validation to one include file and used on both forms.
- a few lines of CSS to support the HTML5 validation. Also within the same include file as previous bullet.
- adopted same layout on most forms
- Fixed an HTML bug on the "message" template that was breaking CD.
- Logs which user failed to reset password in ELK.
- HID-2145: Errors …
=> HID-2131: auth password v3

api/controllers/UserController.js, api/controllers/ViewController.js, assets/css/page.css, assets/css/profile-edit.css, assets/css/user.css, assets/js/profile-edit.js, config/routes.js, templates/profile-edit.html, templates/totp.html, templates/user.html
This branch finishes the profile management section by allowing all aspects of emails to be managed from one screen:
- Add a new email to your profile
- Re-send an email confirmation to unconfirmed addresses
- Delete an email from your profile
I tried to be very thorough in validating form submissions even to the point of editing the DOM and getting around the basic client-side validations. If you can find a way to break it I will be very interested to see what you come up with.
- Trying to set an email as primary with the radio button, then click <kbd>DELETE</kbd> on that same email address
- Edit DOM to send confirmations to confirmed emails
- Edit DOM to delete primary address
- Edit DOM to set an unconfirmed address as primary
I had to tweak the internals of several functions but …
=> HID-2153: manage emails on profile

api/controllers/UserController.js, api/controllers/ViewController.js, assets/css/page.css, assets/css/user-settings.css, assets/js/confirmation.js, assets/js/profile-edit.js, assets/js/tabs.js, config/routes.js, docs/v3/hid.yml, templates/footer.ejs, templates/profile-edit.html, templates/settings.html
This PR allows user's logged into HID Auth to list and revoke OAuth Clients they've authorized for their account.
There was no method to do this internally, and the old system was relying on a JS client to manually modify the user object, then `PUT` the entire user back into the DB.
I didn't like that options, so to facilitate this action internally I created a new API endpoint:
- `DELETE /api/v3/user/{id}/clients/{client}`
- the handler is `UserController.revokeOauthClient`
@orakili if you could review this endpoint and try to break it I would very much appreciate it. There are new docs available at http://api.hid.vm/docs/v3/#/user/delete_user__id__clients__client_ when you're running the API locally.
@left23 the remaining part is again the UX and more adoption of CD components. I've …
=> HID-2009: manage oauth clients on user profile

api/controllers/AuthController.js, api/controllers/TOTPController.js, api/controllers/ViewController.js, assets/css/page.css, assets/css/settings-security.css, config/routes.js, templates/alert.html, templates/header.ejs, templates/settings-password.html, templates/settings-security.html, templates/settings.html, templates/totp-confirm.html
HID Auth users now have 2FA settings available. You should be able to:
- Enable 2FA and it shows up during login, for instance.
- Go back to settings and disable 2FA by again entering a token or backup code.
I updated the following methods but tested them pretty thoroughly and the changes were very small anyway:
- `TOTPController.generateConfig()`
- `TOTPController.generateBackupCodes()`
- `TOTPController.enable()`
- `TOTPController.disable()`
=> HID-2159: manage 2FA settings

api/controllers/AuthController.js, api/controllers/UserController.js, api/controllers/ViewController.js, api/models/User.js, api/policies/AuthPolicy.js, assets/css/page.css, assets/css/settings-delete.css, assets/js/totp.js, config/routes.js, templates/alert.html, templates/profile-edit.html, templates/settings-delete.html, templates/settings-password.html, templates/settings.html
@orakili our TOTP logic for backup codes needed some love. For one, when setting up 2FA via API calls, it's possible to skip the `POST /totp/codes` API call and end up with half-configured 2FA that our `User.backupCodeIndex()` function was choking on. I added a quick guard to check each property in the nested objects to avoid such a heartbreak 💔 
Additionally, backup codes weren't getting removed — even when we logged that they were 🤦 — but that should be cleaned up now as well. To test the halfway 2FA state, run the following calls:
- `POST /jsonwebtoken` (to get your API key)
- `POST /totp/config` it will output a base64 image but also a plaintext config string that you can paste to an Auth app
- `POST /totp` — enable 2FA once your Auth app is generating codes
- Now you're at the …
=> HID-1970: delete account

package-lock.json, package.json, templates/authorize.html, templates/login.html
I added CD-buttons to the Auth prompt. I also changed some words (more details in ticket).
Since setup for this is a royal pain, and we've cross-browser tested the cd-button implementation many times, I submit a screenshot for your inspection  😁
=> HID-2166: auth prompt

api/controllers/ClientController.js, docs/hid.yml, package-lock.json, package.json
Added logging to `ClientController.find()` and also corrected a few discrepancies with docs:
- the default `sort` was actually `_id` but we advertise `name` — it should really be `name` now 
- the default pagination was 50 but it's 100. Docs updated to say 100.
- the logs now list how many records were displayed, and who asked to see them in ELK meta fields
- the pre-existing 404 log also contains the security-related meta fields
Endpoints to test (you must have an HID user who has `user.is_admin=true`:
- `GET /api/v3/client`
- `GET /api/v3/client/{id}`
=> HID-2142: log when listing OAuth client(s)

api/controllers/AuthController.js, api/controllers/ViewController.js, package-lock.json, package.json, templates/error.html, templates/message.html, templates/settings.html
Sometimes HID outputs ugly errors that make it look unstable. It turned out the errors were being displayed that way on purpose (more or less). So this PR fixes the branding issues and makes the error much more user-friendly.
Unfortunately to test this you have to craft an OAuth request. I have a puppeteer script sitting around which lets me skip manually logging in and it autofills forms and stuff. I can put it in a repo if you want, but you can also trigger the Authorization by using the following URL template:
```
GET http://api.hid.vm/oauth/authorize
?response_type=token
&client_id=chris-debug
&client_secret=0123456789abcdefghijklmnopqrstuvwxyz
&redirect_uri=http%3A%2F%2Fchris.debug.test%2Flogin%2Fcallback
&state=12345
&nonce=19207
```
You will have to create that client, or replace …
=> HID-2117: fix ugly errors during Authorization process

commands/createOAuthClient.js, package-lock.json, package.json
we want to create new OAuth clients via jenkins. this new script at `commands/createOAuthClient.js` does that.
Testing locally is done by spinning up the container then running:
```
docker-compose exec dev node commands/createOAuthClient.js
```
It should log success or failure. Searching the list for "change" at http://api.hid.vm/admin will turn up the new entry like so:
=> HID-2190: create new OAuth client via jenkins command

api/controllers/AuthController.js, api/controllers/OutlookController.js, api/controllers/WebhooksController.js, config/main.js, config/routes.js, config/session.js, config/web.js, docs/swaggerBase.yaml, package-lock.json, package.json, plugins/hapi-oauth2orize/index.js, server.js
Please check out the issue for a full description, but long story short I broke this part of HID for _some_ users (but not Drupal, which is why it was hard to track down). I'll comment inline with the major changes since I added tons of comments in the process of debugging.
Since the "extra secure" flow is really difficult to mock, I have been using a local Drupal installation to test. I modified the port of HID to be 8080 and ran the drupal installation on port 80 without any modifications.
Once that is set up, log into Drupal as admin and adjust the `social_auth` config as desired to test various conditions (wrong client ID, wrong secret, etc).
=> HID-2136: prevent 500 during access_token requests

api/controllers/AuthController.js, api/controllers/UserController.js, package-lock.json, package.json
I freely admit this is a change that should require a major version bump, but business-wise we've spent a year communicating this change to our partner websites so I'm cheating a little bit.
Our `account.json` response is being reduced from the entire DB record, to the few fields that are necessary for OAuth to function:
- `id`: HID user ID
- `sub`: defined by OAuth spec to be your unique identifier (internally we duplicate the `id` field)
- `email`: I think this is self-explanatory
- `email_verified`: defined by OAuth spec to report whether the user demonstrated ownership of the account in the `email` field
- `name`: the name of the user
- `iss`: canonical URL of our OAuth service
The OpenID Connect config has also been pruned to reflect our new payload. If we need such properties as …
=> HID-2129: reduce response payload when account.json is requested

api/models/User.js, commands/removeFieldEmailsVisibility.js, docs/swaggerBase.yaml, package-lock.json, package.json
Removes the `emailsVisibility` field. Field remains in CSV export and GSSSync functions.
```
$ docker-compose exec dev node commands/removeFieldEmailsVisibility.js
info: [commands->removeFieldEmailsVisibility] Removed emailsVisibility field from all users level=info, @timestamp=2021-02-23T10:09:34.514Z, ,
> db.user.count({emailsVisibility: {$exists: true}})
0
```
OAuth should still work like usual.
=> HID-1919: remove emailsVisibility field from all users

api/models/User.js, commands/removeFieldWebsites.js, package-lock.json, package.json
Removes the `websites` field from user profiles.
```
$ docker-compose exec dev node commands/removeFieldWebsites.js
info: [commands->removeFieldWebsites] Removed websites field from all users level=info, @timestamp=2021-02-23T10:25:14.228Z, ,
> db.user.count({websites: {$exists: true}})
0
```
OAuth logins should stop working.... not really, just seeing if you read the description 😆
=> HID-1921: remove websites field from all users

api/models/User.js, commands/removeFieldLocations.js, commands/sendReminderCheckinEmails.js, emails/reminder_checkin/fr/html.ejs, emails/reminder_checkin/html.ejs, package-lock.json, package.json
Removes the `location`, `locations`, and `locationsVisibility` fields from all user profiles. References remain in Outlook, GSS, and CSV export functions.
```
$ docker-compose exec dev node commands/removeFieldLocations.js
info: [commands->removeFieldLocations] Removed location, locations, locationsVisibility fields from all users level=info, @timestamp=2021-02-23T10:43:01.206Z, ,
> db.user.count({location: {$exists: true}})
0
> db.user.count({locations: {$exists: true}})
0
> db.user.count({locationsVisibility: {$exists: true}})
0
```
OAuth should continue working as usual.
=> HID-1939: remove location, locations, locationsVisibility fields

api/models/User.js, commands/removeFieldFunctionalRoles.js, commands/updateListUsers.js, config/routes.js, package-lock.json, package.json
Removes the `functional_roles` field from User schema, and code remains in the CSV, GSS, Outlook vestigial functions.
```
$ docker-compose exec dev node commands/removeFieldFunctionalRoles.js
info: [commands->removeFieldFunctionalRoles] Removed functional_roles field from all users level=info, @timestamp=2021-02-23T12:50:55.829Z, ,
> db.user.count({functional_roles: {$exists: true}})
0
```
OAuth should still work.
Feeling like I should tackle these GSS and CSV things so I can stop sounding like a broken record 😆
=> HID-2193: remove functional_roles field from all users

assets/css/login.css, templates/login.html
Adding some "about this site" text to the login form, which currently functions as homepage. People who log into other sites with HID will also see this text next to or under the login form.
@left23 I had a question about the Grid in flowdock but though I'd tag you as a reviewer so you can advise me on specific lines if I am implementing the grid wrong. I'll leave a comment on my workaround I added.
=> HID-2173: add some about text to login page

docs/swaggerBase.yaml, package-lock.json, package.json
I borked the DockerHub image builder and didn't know until now. This script, combined with our weird method of requiring config that uses relative paths, is breaking on account.
Fixing the DockerHub regression caused by 325a7ed
=> OPS-7348: revert the auto-incrementing version in API Docs

docs/swaggerBase.yaml, package-lock.json, package.json, templates/footer.ejs
The trailing slashes weren't compatible with some URLs on GH Pages. Removing them all.
=> HID-2209: remove trailing slashes in CD Footer

api/controllers/ViewController.js, package-lock.json, package.json
Small templating change with big effects on end-users. Their settings pages will now properly link to individual OAuth Client URLs. There was no security problem here because the bug's affect was to link to https://auth.humanitarian.id/someurl.org which 404s on HID and looks ugly, but never sent people to a strange place on the internet.
Load your user settings where it lists your authorized OAuth Clients and view source to manually verify that URLs are well-formatted. They were already working fine during local testing which allowed this bug to slip through. Click one or two and confirm that they still link to the intended location.
=> HID-2211: add slashes to manually-constructed top-level URLs

api/controllers/AuthController.js, package-lock.json, package.json
I was logging the wrong value for `hid.oauth.client_id` in Kibana. Now it will log something like `ocha-gho-local` instead of a 24-char hex string.
=> HID-2210: log human-friendly OAuth Client ID when new authorization happens

templates/new_password.html, templates/register.html, templates/settings-password.html
Removing autocomplete from new-password fields. There's basically nothing to test given that this is browser-facing HTML, but go ahead and run the Login E2E if you want.
=> HID-2217: remove browser autocomplete for new passwords

config/web.js
Stage is our default environment and it needs to be allowed.
=> HID-2218: ensure API docs work by default

assets/css/cd-tag.css, assets/css/page.css, assets/css/profile-edit.css, assets/css/profile-show.css, templates/profile-edit.html, templates/profile-show.html
Enhancing the ongoing CD v3 work with the new CD Tag.
I had to adjust tag colors to be darker based on a11y feedback from Lighthouse. I feel like long term we should probably raise this to Javi and see if we can adjust the color scheme "from the top" instead of having to balance on-brand with accessible.
The branch also fixes some focus issues. I had to dig back through CD commit history but it seems a bunch of variables were renamed (e.g. `--cd-bright-blue` which effectively removed focus styles from the website, since the value no longer existed.
=> HID-2202: CD Tag labels instead of disabled buttons

assets/js/confirmation.js, assets/js/profile-edit.js, assets/js/settings.js, docs/swaggerBase.yaml, package-lock.json, package.json, templates/profile-edit.html, templates/settings.html
I realized another missing piece of UX due to the CSP. The confirmation dialogs should be restored in these two situations: 
- Deleting emails from your profile. URL: `/profile/edit`
- Revoking OAuth Clients. URL: `/settings`
=> HID-2218: CSP-allowable submit handlers

api/controllers/ViewController.js, config/web.js, docs/swaggerBase.yaml, package-lock.json, package.json
Post-launch I noticed that in our remote environments, GA was being blocked by our new CSP on account of `data:` not being allowed. This seems to work on dev when I deployed a feature branch.
We've also noticed reCAPTCHA is no longer working and that's also due to the CSP.
=> HID-2226: GA wants to load more code via data URI

api/controllers/AuthController.js, docs/swaggerBase.yaml, package-lock.json, package.json
Sometimes we show a redirect URL when the partner site had a configuration error. This is a templating change to prevent us from linking anywhere except an official redirect URL that we store inside HID.
The easiest way to test this is by falsifying an OAuth Client within HID and leave your Drupal site as-is:
- If necessary, reset the password for a known admin account using the included Mailhog instance.
- Log in as admin, and go to `/admin` to see the list of Clients
- Edit the entry for your chosen OAuth Client, falsifying both the `redirect_uri` and `redirect_urls` fields.
- Try logging in with Drupal and ensure that the value displayed is from the HID DB, and NOT from the Drupal site's `redirectUri` value:
=> HID-2224: always redirect to official URLs for partner sites

.eslintrc.js, package-lock.json, package.json, server.js
We're removing NewRelic from our dependencies because it is baked into the node.js image, as discussed in OPS-7464
=> HID-2235: remove newrelic from our dependencies

commands/createOAuthClient.js, docs/swaggerBase.yaml, package-lock.json, package.json
Preventing a rare potential error before it bites us. Randomizes the `client_id` of a new OAuth Client since we generate them via Jenkins. Now you can run the job multiple times (say you want dev/stage/live) and it is quite unlikely to create collisions.
Run this command inside the `api` container a couple times in a row:
```sh
docker-compose exec api node commands/createOAuthClient.js
```
Old behavior would have had errors on the second time and afterwards. PR should be able to run it essentially unlimited number of times. 308,915,776 times to be exact.
=> HID-2233: ranomize new  OAuth Client IDs

assets/css/cd-button.css, docs/swaggerBase.yaml, package-lock.json, package.json
Temporarily applies `cursor: pointer;` to CD Buttons. Upstream PR to fold this into CD: https://github.com/UN-OCHA/common_design/pull/244
=> HID-2228: set cursor:pointer on all CD Buttons

_tests/e2e/_env/example.js, api/policies/AuthPolicy.js, config/routes.js, docs/swaggerBase.yaml, package-lock.json, package.json
We used to serve HTTP 200 with an empty object `{}` when the Authorization header was missing or invalid. Then at some point the API started serving HTTP 500, I would guess when we changed the payload that gets sent for v3.
This PR brings us in line with the [official OpenID Connect spec](https://openid.net/specs/openid-connect-core-1_0.html#UserInfoError) by returning HTTP 401 for both missing and invalid tokens. I also updated the [appropriate wiki section](https://github.com/UN-OCHA/hid_api/wiki/Integrating-with-HID-via-OAuth#step-3--request-user-account-info) with an example.
Visiting `/account.json` in your browser should now produce HTTP 401 instead of 200 or 500. Sending the Authorization header, or logging in with Drupal should (naturally) produce the user account.
The other stuff …
=> HID-1997: account.json error

api/controllers/ViewController.js, package-lock.json, package.json, templates/error.html
We got a report that someone saw what looks like a 500 error during password reset. It's just uninformative, and on top of that we weren't logging anything when there was a real error.
E2E passed on my local. To test you can do two things:
- Visit http://auth.hid.test/new_password - should show a red error with a link to reset your password
- Successfully reset your password after clicking the link. Mailhog is at http://localhost:8025
=> HID-2248: better errors and logging for password resets

_tests/e2e/PasswordReset.test.js, api/controllers/UserController.js, api/controllers/ViewController.js, api/models/User.js, config/routes.js, docs/swaggerBase.yaml, package-lock.json, package.json, templates/error.html, templates/password.html
Remember when we discussed changing these endpoints way back when? I finally did it. This PR eliminates the following endpoint:
- `PUT /api/v3/user/password`
And in its place we have two new ones:
- `POST /api/v3/user/password-email`
- `POST /api/v3/user/password`
Internally I also split the functions that handle these, and bumped the major version to reflect that change.
With all of that cleanup done, I also provided some UX improvements to the Auth website. It will immediately fail on invalid password links. It used to let you try to reset, only informing you afterwards that the link was invalid. 2FA people also had to submit a code, filling out two forms before finding out the bad news.
Now it fails instantly and points you to the form where you can start over.
<del>There are a couple …
=> HID-2249: immediately fail on invalid/expired password links

_tests/e2e/Login.test.js, _tests/e2e/PasswordReset.test.js, _tests/e2e/ProfileEmails.test.js, _tests/e2e/_env/index.js, _tests/e2e/_utils.js, api/controllers/UserController.js, api/controllers/ViewController.js, api/services/EmailService.js, config/routes.js, config/web.js, emails/email_validation/html.ejs, templates/profile-edit.html, templates/profile-show.html
Marking as a draft until the open PRs are merged.
I split the route into two pieces and since we're incrementing the major version on next deploy, I took the liberty of shoving all the breaking changes into one branch.
The following endpoint is gone:
- `PUT /api/v3/user/emails/{email}`
In its place are two new ones:
- `POST /api/v3/user/emails/{email}`
- `POST /api/v3/user/emails/validate`
Not only was `PUT` inaccurate (since the email message it triggers is unique each time) but the code no longer serves two functions based on the payload you send.
- Use API to create an email, and copy data out of Mailhog to craft the second API request.
- Use website to create an email, and click the email link to confirm an address.
Brand new E2E awaiting you, hopefully to reduce manual clicking and …
=> HID-2064: split email confirmation into two routes

api/controllers/UserController.js, api/controllers/ViewController.js, api/services/EmailService.js
Previously, when you added a recovery email to your account, every email on your profile got a message notifying you about it. The PR prevents unconfirmed addresses from getting such messages.
1. On your local, delete all the recovery emails on a test account of your choosing, so that only the primary remains.
2. Now, add a recovery email to that account. Auth or API calls are both fine. Do NOT confirm it by clicking link in Mailhog.
3. Add another recovery email (skip confirmation)
4. Add another recovery email (skip confirmation)
5. Check Mailhog and see that only _confirmed_ addresses are getting emails with subject line "Security alert for your HID profile" — it should be one per recovery email which will be mentioned in the message body.
=> HID-2150: avoid sending email_alert messages to unconfirmed recovery addresses

api/controllers/UserController.js, api/controllers/ViewController.js, assets/js/passwords.js, templates/alert.html, templates/new_password.html
This started out as a small fix for the CSP, which disabled our client-side validation.
Since that happened, I'd actually noticed some intermittent errors during password resets and never could figure out what it was. It ends up that we weren't enforcing the `confirm_password` field on the server, which combined with lack of client-side validation, meant it was possible to change your password to something unexpected.
PR fixes both problems: we now have both server- and client-side validation, instead of nothing at all 🙈 
This also conveniently gets included in the 4.0.0 release, since the `confirm_password` property of the payload is now required.
Basically, just reset a user's password and fill the form out incorrectly in various ways. It should now stop you from doing anything except …
=> HID-2255: server-side validation of password reset, plus restore client-side validation

api/controllers/AuthController.js, api/controllers/ViewController.js, templates/message.html
At some point I changed a conditional from checking truthiness, to checking if it existed at all. That was a no-no, and caused messages to show up when they shouldn't. In this case, when you deleted your account, the website said you can now login to HID.
After removing the instances of `isSuccess: false` which was causing it to show up _specifically when it shouldn't_, I realized there is one instance of the template left. That's after password reset. I think people will know that they can login after resetting their password, so I removed the whole thing.
Reset the password of a random account, login with it, and delete the account. At each step, the user feedback should function, and no templating errors should occur.
=> HID-2261: remove isSuccess variable from message.html

api/controllers/AuthController.js, api/controllers/UserController.js, api/policies/UserPolicy.js, config/routes.js
We restricted the API a little too much when we removed searching capabilities from HID Contacts. This PR restores any user's permission to GET themselves from the API.
1. Request `GET /api/v3/user/{id}` from a regular, non-admin user. It should return the user's object as long as you send your Bearer token.
2. Change the value of `{id}` to some other value without changing the number of characters (i.e. replace any `1` with a `2`) and it should respond with 403 Forbidden.
3. Use an admin account to search for any individual user ID. All user IDs, including your own, should work.
=> HID-2262: adopt and simplify UserPolicy.canUpdate

api/controllers/AuthController.js, docs/swaggerBase.yaml, package-lock.json, package.json
Final cleanup for HIDv3 migration. Removes the following fields from `account.json` so that we can complete our DB pruning:
- `given_name`
- `family_name`
- `user_id`
=> HPC-7918: remove deprecated fields from account.json

api/controllers/AdminController.js, api/controllers/AuthController.js, api/controllers/TOTPController.js, api/controllers/ViewController.js, api/policies/AuthPolicy.js, config/web.js, package-lock.json, package.json
We found that HID has an implicit dependency on the load balancer cookies. It turns out that the session management library, `yar`, allows us to store session data up to a certain amount, 1KB. Once you exceed that limit, it starts dumping the data to a server cache, which uses container memory as its default backend.
If the load balancer stickiness gets disabled, OR if we had to scale up HID API containers due to heavy load, the user's session data has a high chance of appearing to not exist. The UX of this bug is ugly, resulting in people seeing a login form after already being logged in. Or sometimes, it looked like the login form wasn't working when the cookie limit got exceeded during login itself.
The PR enables a Redis backend for the session storage, so that all API containers can …
=> HID-2260: implement session storage backend using Redis

api/controllers/AuthController.js, commands/readCookie.js, package-lock.json, package.json
⚠️  This branch uses #291 as its base. It will be in Draft until that PR is merged ⚠️ 
This PR attempts to protect against some types of session hijacking, by resetting the session once a user successfully logs in. The result is that even if you stole a user's cookie during login, it won't be any good by the time they submit the form and finish the login process. They'll have a new ID and the old one won't exist.
I added a new "command" to make testing this easier. It uses the stack environment to decrypt cookies that you receive in your browser.
1. Load HID login form in browser. Copy the `session` cookie from devtools.
2. `docker-compose exec api node commands/readCookie.js --cookie="__PASTE__"` — note the session ID that gets output.
3. Now login using the HID form. Once the page shows …
=> HID-2216: implement one remediation measure against session fixation

api/controllers/AuthController.js
We asked around the team and also checked the logs. The affected variable which everything was using does not seem to ever be present in our requests nowadays.
Nevertheless I marked it as a breaking change and it will bump our API's major version. I would have liked to group it into the current release but oh well.
As a bonus, I looked into the token-to-user stuff and got the OAuth Client ID coming through via `request.auth.artifacts` which is now logged on each request to `/account.json` when you use a short-lived OAuth token.
- **Make sure Drupal login still works.** It should log the OAuth `client_id` of the website when it logs "[AuthController->showAccount] calling /account.json for ..."
- **Make sure `GET /account.json` still works with your personal JWT** (this is technically not …
=> HID-2192: remove special cases from /account.json

api/controllers/UserController.js, api/models/User.js
During our annual security self-assessment for OICT, this stood out as the only relevant item we don't implement. Their guidance says that users should not reuse the previous five passwords.
- Changing password via API call should behave almost identically, but you can no longer switch between two passwords like you used to be able to. Passwords can no longer be reused and the error code remains the same, but the message says "New password must be different than previous passwords" — the old response used to be "New password is the same as old password."
- While logged-in, using the password change form at `/settings/password` will tell you that a password cannot be reused (same error text as API response)
- If you try to re-use passwords when resetting passwords via email links, it will …
=> HID-2276: store historical password hashes and prevent re-use

templates/totp.html
Minor a11y/html bug: TOTP form has a checkbox to remember a device for 30 days. It was missing a `<label>`.
2FA form should look unchanged. This is so minor that I'm just merging without review, but FYI @orakili
=> HID-2264: on TOTP form, checkbox to remember device now has a label

api/controllers/ViewController.js
I noticed that redis was holding onto some session data after a password reset took place. That shouldn't happen. PR resets sessions after password reset form is submitted. The outcome (success/error) doesn't matter. The session always gets wiped.
I also cleaned up code as went: commented parts of the function, used a better DB lookup, renamed vars to be clearer.
The cookie that gets set when you load the password reset form (with the two password fields), should be destroyed after the form gets submitted.
1. use password reset form, click link in mailhog, open devtools for the tab and **refresh** to get a `Set-Cookie` header to decrypt
2. decrypt the session using `commands/readCookie.js` and get ID
3. look up ID in redis: `doco exec redis redis-cli`, `select 10`, `keys *`, `get …
=> HID-2277: destroy session when submitting password reset form

_tests/e2e/PasswordReset.test.js, _tests/e2e/Register.test.js, api/controllers/ViewController.js, emails/register/html.ejs, templates/register.html
When you sign up and click the initial confirmation link, Prod currently says it's malformed. However, it DOES confirm the account and it DOES email you saying "this was successful" problem was in the code to display the success message.
Due to my own oversight, I was trying to write to a cookie object which wasn't guaranteed to exist. If you ask for the session object and none exists, it returns `null` which JS considers truthy 😠 
I patched up the problem, plus dropped an actual logging statement in our `catch` so that maybe next time I write bad code, we can see a stack trace in ELK.
New E2E test `Register.test.js` does this:
- Open private/incognito browsing session in browser of your choice.
- Register new HID account
- Click confirmation link in mailhog
- It should report success now
=> HID-2292: don't show errors when everything worked just fine

_tests/e2e/PasswordReset.test.js, api/controllers/UserController.js, api/controllers/ViewController.js, templates/new-password.html
The password reset process is hopefully a lot smoother now. When you fail to meet all password requirements (complexity or re-use) the error is more specific and it now shows the password reset form, instead of forcing you to generate a new link and start over from the beginning.
When you're successful, it drops you directly on the login screen.
Test the process with 2FA/non-2FA.
1. Reset password with regular user. Note the password you choose.
2. Do another password reset. Use SAME password. It should show the following:
3. Enter a new, valid password. It should show the success message on the login page now:
=> HID-2288: show password form again when any pw requirement wasn't met

_tests/e2e/Login.test.js, _tests/e2e/ProfileEmails.test.js, _tests/e2e/_env/example.js, _tests/e2e/_utils.js, api/controllers/AuthController.js
Allowing confirmed recovery addresses to be used for login will solve a ton of support problems, in addition to allowing simplification of language across the website. There's no additional security risk because the user still has to demonstrate ownership of the email address before it can be used for login.
Per usual, there's no specific feedback in regards to why your login gets rejected. It all gets condensed into one canned response, in order to comply with OICT and follow the recommendations of our recurring independent security audits.
```sh
npm run e2e -- -t Login
```
There are new tests which attempt the following scenarios:
- non-existent address: PREVENT login
- unconfirmed recovery used to login: PREVENT login
- confirmed recovery used to login: ALLOW log in
To get these …
=> HID-2300: allow confirmed recovery email addresses to be used for logins

emails/email_alert/fr/html.ejs, emails/email_alert/html.ejs
When a person adds a new recovery email address, we notify them by emailing all confirmed addresses on their profile. This PR updates the wording.
Add an email address to any account. Note the changes to the notification in Mailhog.
The concept of non-EN locales is vestigial from HID Contacts, but nevertheless it exists. Some 4000 users still get french emails. To find a french user, run this command in the Mongo console:
```sh
> db.user.findOne({ locale:'fr'},{email:true})
... result will display an email...
```
=> HID-2299: update text within email_alert notifications

emails/admin_delete/fr/html.ejs, emails/admin_delete/html.ejs, emails/email_alert/fr/html.ejs, emails/email_alert/html.ejs, emails/email_validation/fr/html.ejs, emails/email_validation/html.ejs, emails/includes/footer_fr.ejs, emails/post_register/fr/html.ejs, emails/register/fr/html.ejs, emails/reset_password/fr/html.ejs, emails/reset_password/html.ejs
This is a follow-up of https://github.com/UN-OCHA/hid_api/pull/318 that fixes the wording in the French email templates.
It also attempts to make the "introduction" (Dear...) and "closure" (Kind regards...) more consistent.
Finally, there was an issue with the footer inclusion of the French alert emails that caused not to be sent.
**Note:** For the French template, `Cher` was changed back `Bonjour` to be gender neutral.
Same as https://github.com/UN-OCHA/hid_api/pull/318
=> HID-2305: Further email fixes.

CHANGELOG.md, docs/swaggerBase.yaml, package-lock.json, package.json
We'd tagged `v5.0.0` and during our 2-week stage window, I noticed a regression. I tagged a hotfix and that was `v5.0.1` and this folds it back into our `dev` branch.
=> Merge hotfix from previous release cycle

Dockerfile, api/controllers/UserController.js, api/models/User.js, package-lock.json, package.json
The PR implements cracklib via node.js directly inside the API container. When choosing a new password we now compare to a dictionary which also does some normalization to convert 0 to o and other similar substitutions that don't provide much security to dictionary words. It has the option to compare to custom strings in addition to its dictionary and we're passing in the following successive strings:
- Given name
- Family name
- Each email address on the profile (regardless of confirmation status)
@teodorescuserban tagging you to see if I did the docker stuff correctly. I believe it's good, because I deployed this branch to dev and everything looks like it works, including logs in ELK for dev env. Still, your 👀  are appreciated.
@orakili theoretically, rebuilding the API container will …
=> HID-2279: implement password dictionary test whenever passwords are being chosen

api/models/OauthToken.js, api/services/JwtService.js, config/web.js, plugins/hapi-auth-hid/index.js
The PR itself could have been tiny, but in the process of debugging and testing I realized there's a whole set of operations relating to this process that don't log any activity. So I added some logs too.
1. Log into a local Drupal website of your choice using local HID. The login must succeed so that you can see your username inside the Drupal website.
If you get GuzzleHttp errors, you probably need to add an entry to `/etc/hosts` to point `hid.test` to the container's "external network" IP. I normally find that by running: `/sbin/ip route|awk '/default/ { print $3 }'`
2. Log into HID as an admin, and edit the `iasc-dev` client to note all the credentials, plus add a redirect URL of your choice that points to the local Drupal setup from (1).
3. With the credentials you found in (2), …
=> HID-2281: remove IASC special-case

api/controllers/AuthController.js, api/controllers/ClientController.js, api/controllers/TOTPController.js, api/controllers/UserController.js, api/controllers/ViewController.js, api/models/User.js, api/policies/AuthPolicy.js, config/env/index.js, config/web.js, docs/swaggerBase.yaml, package-lock.json, package.json
Some cleanup as we upgrade the MongoDB library we're using inside node.
In general, if you see any mention of Mongo deprecations in the console, this PR needs more work.
- Login _incorrectly_ on an existing account more than five times in five minutes and make sure no deprecation warnings spring up relating to `count()`
- Use Auth to delete a user account.
- Any API call with `DELETE` verb should be tested: a user account, TOTP trusted devices, OAuth Clients, API keys, etc.
=> HID-2257: upgrade mongoose to 6.x

api/controllers/UserController.js, api/policies/UserPolicy.js, config/routes.js
We had a PR a while back where the point was raised that UserPolicy does content validation. This is my effort to clean it up and provide clear separation of concerns.
- `UserPolicy` does permission checks only, and returns a simpler set of response codes.
- `UserPolicy.canDestroy` was consolidated since after cleanup it had identical permission checks to `canUpdate`
- `UserController.create` now handles content validation specific to this function
- `UserController.destroy` now protected by a policy, and outputs simpler error codes.
Regular users
- Create a new user and verify the account by clicking confirmation email.
- Confirm that it **can** view itself: `GET /api/v3/user/{id}`
- Confirm that it **can** delete itself: `DELETE /api/v3/user/{id}`
Admins
- Find an admin user
- Confirm …
=> HID-2267: clean up UserPolicy

api/controllers/ViewController.js, package-lock.json
No new logic, but when I implemented cracklib for user registration, I changed the errors coming out of `UserController.create()` and didn't update `ViewController.registerPost()` to scan for the new strings.
- Create new user account (don't forget to comment out the reCAPTCHA challenge in ViewController submit handler)
- Enter a valid, but weak password, like `123456789aA!` in both fields
- The form should prevent registration and display a warning:
> Your password was not strong enough. Please check the requirements and try again.
- Open your devtools and momentarily disable JS, then refresh the page to try a second registration.
- While filling the form, enter **two different passwords**.
- The form should prevent registration and display a warning:
> Your password fields did not …
=> HID-2327: fix regression related to user-friendly registration errors

api/models/OauthToken.js
We were logging the DB id instead of the OAuth client ID when generating OAuth tokens. To confirm fix, log into a Drupal site with HID and scan the logs to confirm that we're outputting human-readable values for `oauth.client_id` when the various tokens get generated:
```
hid-api-1  | {"oauth":{"type":"refresh","client_id":"ocha-2022-gho-unocha-org-local"}..."message":"[OauthToken->generate] generating refresh OAuth token"...
hid-api-1  | {"oauth":{"type":"access","client_id":"ocha-2022-gho-unocha-org-local"}..."message":"[OauthToken->generate] generating access OAuth token"...
```
Fixes regression introduced in https://github.com/UN-OCHA/hid-api/commit/8c7f91d9786ae0aab59d1cc301a25a2e604b36f0#diff-782db861e1fe49c725579627e013a575c81ad7aafa7f316247c35a3ea2d25636R73
=> HID-2336: supply correct client_id value when generating OAuth tokens

package-lock.json, package.json
Two investigations indicate that the 'lazy' mode of `yar` was the source of problems within our `oauth2orize` plugin, leading visitors who confirm an OAuth connection to see an error some of the time.
[We forked the library](https://github.com/UN-OCHA/yar) and are using it as our dependency while we await a resolution to the upstream PR.
=> [HID-2320] prevent errors during OAuth dialog confirmations

package-lock.json
Switches to master branch of our `@hapi/yar` fork. Previously we were pointing at our internal PR branch, and I _think_ the package-lock.json will favor the commit hash it has listed over the specific branch name, but I'm cleaning this up to be extra certain.
=> [HID-2320] reinstall to update package.json

.github/workflows/build.yml
So we turn them off, which will fail the build if someone tries to sneak one in. Win-win!
=> build: Submodules are a bad idea and make many people very angry.

templates/settings-delete.html, templates/settings-security.html
Fixes the include paths for a few settings pages. The "delete account" page is for admins only, so very low impact on prod. The other page does indeed prevent 2FA from being enabled on all environments.
@lazysoundsystem you can go ahead and give this a YOLO and we'll test it on dev, where the problem is currently reproducible.
=> [HID-2361] correct paths for alert include within settings pages

CHANGELOG.md, package-lock.json, package.json
* correct paths for alert include within settings pages ([fb5dd80](https://github.com/UN-OCHA/hid-api/commit/fb5dd80ad4d84c8e2c53a6f8905386dd8441448a))
* update tracking code to use GTM/GA4 ([1be35f2](https://github.com/UN-OCHA/hid-api/commit/1be35f2a8a945b98524b1c64c44f9e8fd3d0b651))
* Use the shared build action with tagging, notifications and pushing. ([fabb069](https://github.com/UN-OCHA/hid-api/commit/fabb0697a9df84dc08c5af0c28923f61d190c0c4))
=> chore(release): 5.1.8

docs/swaggerBase.yaml
We won't know the next version until we cut a release but at least it matches the latest version that exists.
Refs: HID-2362
=> chore: bump public-facing API version indicator

config/web.js
Refs: HID-2354
This adds CSP exceptions we include in the Drupal sites - but not the 'unsafe-inline' exception - which may be covered by the hash which is included already. Needs testing.
=> fix: add csp settings

api/controllers/UserController.js, api/models/User.js, api/policies/AuthPolicy.js, config/routes.js, package-lock.json
Endpoint force-resets a user's password to something random. The admin never has access to the account, and it can't ever see the password either.
Afterwards, the target user must perform a successful password reset via email link in order to regain access to the account.
1. Generate new docs by running `npm run docs` inside container.
2. Generate a JWT for an admin within your local DB.
3. `POST /api/v3/user/{id}/password-admin` via [local swagger](http://hid.test:8080/docs/#/user/post_user__id__password_admin)
Additional confirmation can be observed by logging into HID successfully beforehand with the target user, then confirming that the same password no longer works after the reset (UI won't say why, but logs will specifically confirm wrong password).
=> [HID-2372] new endpoint to force-reset user passwords

CHANGELOG.md, package-lock.json, package.json
* regular security updates
* **ci**: migrate from Travis to GHA
=> chore(release): 5.2.1

CHANGELOG.md, docs/swaggerBase.yaml, package-lock.json, package.json
* **security**: regular security updates
=> chore(release): 5.2.4

api/controllers/NumbersController.js, config/routes.js
Admin-only endpoint for aggregate user counts.
- `GET /api/v3/numbers`
- No token or non-admin token should 403
- Bad token should 401
- Admin token should 200 with a JSON object:
```json
{
"totalUsers": 321,
"emailVerified": 123,
}
```
=> [HID-2387] user counts

CHANGELOG.md, CONTRIBUTING.md, docs/swaggerBase.yaml, package-lock.json, package.json
* aggregate user counts via API ([946a189](https://github.com/UN-OCHA/hid-api/commit/946a189b6f243dfa891ae2ee3d4aa3fccc105a45))
* add logging to the deleteExpired commands ([88c4892](https://github.com/UN-OCHA/hid-api/commit/88c48928a7b5836dba3cda73057e5823d99f3e9c))
* **admin:** enforce admin perms on OAuth Client edit submissions ([dea1267](https://github.com/UN-OCHA/hid-api/commit/dea1267ba22292c7eb4f260f6b9d1a5bb726df55))
* adopt CD Layout classes on all templates ([aa4560a](https://github.com/UN-OCHA/hid-api/commit/aa4560a18ae723b0e96319faa07b7583808dc8eb))
* apply mustard cut exactly like Drupal ([65c3b92](https://github.com/UN-OCHA/hid-api/commit/65c3b921ae658e1626f6b4dd1dc644b3093c0259))
* better namespace for user dashboard …
=> Release 2023-06-01

CHANGELOG.md, docs/swaggerBase.yaml, package-lock.json, package.json
* Sigh. ([3bd603f](https://github.com/UN-OCHA/hid-api/commit/3bd603f216ae5282ac4756ef473d5f090e4a00fa))
* Use slack channel from vars, so dependabot can see it. ([46cfef0](https://github.com/UN-OCHA/hid-api/commit/46cfef0490a600ca2046862fc11e8dfaa69af070))
=> chore(release): 5.3.1

server.js
The value we set is the current default for Mongoose 6, but the default will change to false in Mongoose 7. Therefore the warning was popping up.
The more conservative option is false, meaning invalid query parameters do NOT result in entire collections getting returned.
Refs: HID-2395
=> fix: explicitly set DB option to suppress deprecation warning

CHANGELOG.md, package-lock.json, package.json
- **security:** bump follow-redirects from 1.15.2 to 1.15.4 ([eb5dbcf7](https://github.com/UN-OCHA/hid-api/commit/eb5dbcf7a5017a02a59c1347e8b5cf85c4524ea3))
=> chore(release): 5.3.5

CHANGELOG.md, CONTRIBUTING.md, docs/swaggerBase.yaml, package-lock.json, package.json
* **a11y:** replace redundant role with aria-label on main tags ([297acc7](https://github.com/UN-OCHA/hid-api/commit/297acc7f806b61613b7699c97159268487f8f683))
* **a11y:** update landmark roles with labels ([4a492d1](https://github.com/UN-OCHA/hid-api/commit/4a492d1374e4a96e6827e001141ee9056487f85e))
* **security:** new GTM hash for CSP ([aeb1e07](https://github.com/UN-OCHA/hid-api/commit/aeb1e07d027a040f96412260b5d29f7f0aabb984))
* **CD:** compile CSS ([b1961ac](https://github.com/UN-OCHA/hid-api/commit/b1961ac204c673695680ac459c2db0c03c722b0d))
* **CD:** update CD Alert markup ([ba43e82](https://github.com/UN-OCHA/hid-api/commit/ba43e82872e36ab4809ddad790f5b245454413c9))
* **CD:** update OCHA logos ([acb00c3](https://github.com/UN-OCHA/hid-api/commit/acb00c39e3a742569e49279b29272a241d746 …
=> chore(release): 5.3.7

config/web.js
The production valkey is shared. It is anyway more secure to not let logins remain active for a week. A day means someone remains logged in over night, but if they are away for the weekend they need to enter credentials again. That seems not unreasonable. Also, sites should not be using HID any more, so it may as well get slightly less convenient.
And it saves us on valkey usage alerts :-)
Refs: HID-2434
=> chore: Reduce valkey storage use by reducing the cookie ttl.
