UN-OCHA/hid-api

- docker-compose.yml
I had permissions issues when linking the db folder directly, and nesting it inside of data seems to have fixed it.
> Use 'data' folder instead of 'db' folder

- Dockerfile
- api/controllers/CronController.js
- api/controllers/UserController.js
- docker-compose.example.yml
- run_node
- update the example docker-compose (remove "link" and update nodejs version)
- added minimal Dockerfile.
- fix travis errors
- customize node startup script so that it skips the `npm install`
> [OPS-4852] improve stack and deploy

- .editorconfig
- .eslintignore
- .gitignore
- config/env/local.js
- config/web.js
- docker-compose.example.yml
- package.json
- server.js
We're continuing my local setup using docker and need to keep some config files fresh. Tagging @guillaumev so he can continue debugging, plus tagging @teodorescuserban to make sure our docker stuff is 👍
> HID-1804: setup + docs v2

- .editorconfig
- .eslintignore
- .gitignore
- commands/verificationExpiryEmail.js
- config/env/local.js
- config/web.js
- docker-compose.example.yml
- emails/forced_password_reset/fr/html.ejs
- emails/forced_password_reset/html.ejs
- emails/forced_password_reset_alert/fr/html.ejs
- emails/forced_password_reset_alert/html.ejs
- emails/forced_password_reset_alert7/fr/html.ejs
- emails/forced_password_reset_alert7/html.ejs
- package.json
- server.js
- HID-1804: some developer docs for onboarding
- HID-1807: email notification template updates
- HID-1802: ensure that verification_expire is only sent once
> Production Deploy 2019-06-26

- .gitignore
- CONTRIBUTING.md
Some notes I wrote down during my first-time setup of the local environment for the API.
> HID-1804: developer docs

- CONTRIBUTING.md
While trying to restore the prod DB for HID-1811 I had trouble following my previous docs. A quick chat with @guillaumev set me straight but I wanted to fix the bad instructions I wrote before.
> HID-1804: fix incorrect docs

- CONTRIBUTING.md
Docs related to some fun I had today testing the App PR 🎊
> HID-1804: document local API issues re: gsssync table

- .travis.yml
- LICENSE
- package.json
Attempting to setup Travis. Starting with linting only.
> OPS-5800: enable Travis

- api/controllers/AuthController.js
- templates/authorize.html
Changed the code according to the comment in HID-1806, which I agree improves the code, but I'm not sure this will fix the issue...
> HID-1806 - user profiles show same auth client multiple times

- config/web.js
This fixes the OIDC implicit flow when requesting an id_token
> HID-1829 - Fixed issue with OIDC implicit flow (id_token)

- docker-compose.example.yml
- package.json
We will have to see with @teodorescuserban if it's possible to run "npm start" on production and dev, but run "npm run dev" on our local environments to have it run with nodemon...
> HID-1804 - Added mailhog to docker-compose example file and nodemon

- plugins/hapi-auth-hid/index.js
> HID-1844 - OP-UserInfo-Body

- package-lock.json
- package.json
> HID-1867: update dev dependencies

- package-lock.json
- package.json
Couple more updates flagged by GitHub.
> HID-1867: more updates to DB dependencies

- assets/css/main.css
- templates/pdf/printList.html
Regression caused by HID-1822.
> HID-1882: PDF styles

- assets/css/main.css
- templates/pdf/printList.html
- templates/pdf/printMeetingComfortable.html
- templates/pdf/printMeetingCompact.html
Updating styles once more, plus fixing the incomplete work for HID-1865 to change disclaimer. List of changes in the branch:
- Running HTML Prettify to ensure consistent HTML indentation across all files.
- Adding required HTML tag attributes (lang/dir)
- Enforcing HTTPS on all Google Fonts links and Footer URLs to HID itself
- Updating disclaimer test according to HID-1865
> HID-1882: PDF styles round 2

- assets/img/icons/user--white.svg
- templates/header.ejs
Restoring other CD Global Header elements, and adding GA to track their use.
> HID-1878: address Global Header inconsistencies

- templates/pdf/printList.html
Trying to get certain characters to render when they get sent to Snap.
> HID-1883: avoid escaping certain fields to play nicer with Snap

- templates/pdf/printMeetingComfortable.html
- templates/pdf/printMeetingCompact.html
Applying the PDF fix to two other templates.
> HID-1883: unescape HTML for meeting templates as well

- commands/createDummyClient.js
- commands/createDummyUser.js
- package-lock.json
- package.json
Allow named arguments so you can do
```docker-compose exec dev node ./commands/createDummyClient.js --url=https://iasc8.local.docksal/ --redirectUrl=https://iasc8.local.docksal/user/login/hid/callback```
> Allow named arguments

- api/services/HelperService.js
Just a patch until we deliver the real fix. To unblock @teodorescuserban setup work.
> HID-1894: stop-gap to get AWS dev sites running

- commands/decommissionEmailsAuth.js
> HID-2021: maybe send Auth email to Auth users

- emails/decommission_profile/fr/html.ejs
See https://github.com/UN-OCHA/hid_api/pull/85#discussion_r408516235
> HID-2021: more french corrections

- api/controllers/UserController.js
- api/models/User.js
- config/routes.js
- package.json
Introduce new v3 method for changing user passwords, which has increased complexity requirements.
> HID-2016: v3 password strength

- api/services/EmailService.js
- commands/decommissionEmailsAuth.js
- commands/decommissionEmailsProfile.js
I had copied another email-related command file and didn't bother checking what I was sending to the email templating engine. All fixed up.
Assigning reviewers FYI but not waiting on approval. Needs to be tested in Jenkins.
> HID-2022: fix tpl issues and allow emails to log failures

- api/services/HelperService.js
More whitelisted domains. Grumble.
@teodorescuserban purely FYI. I'm merging without review.
> OPS-6441: add additional domains for AWS migration

- api/models/User.js
New environment, new hardcoded domain.
> HID-2035: add another domain for AWS migration

- assets/css/main.css
Build artifact of un-ocha/hid_app2@ee2dadd31fa337872e7162e148559a61b68be804
See our jira ticket for before/after.
> HID-2057: update CSS to include alerts on Auth pages

- api/services/HelperService.js
We have a new environment and we are hardcoding these dumb things.
> OPS-6301: add yet another set of authorized domains

- CONTRIBUTING.md
- docs/specs.yaml
Updating v2 docs to point at our current dev environment.
> HID-2055: update Dev environment URL for swagger docs

- README.md
- api/controllers/AuthController.js
- api/controllers/UserController.js
- api/models/JwtToken.js
- api/policies/UserPolicy.js
- api/services/JwtService.js
- config/routes.js
- docs/specs.yaml
- docs/v3/hid.yml
- docs/v3/swaggerBase.yaml
Big docs PR, plus some other minor fixes that either needed to happen to avoid breaking things, or were small enough that I just didn't feel like waiting:
- HID-2061
- HID-2063
Other tickets filed during the course of this work will be ready for review separately.
I did rearrange the order of some endpoints because I personally felt like it was easier to scan when I read the docs page. All sub-paths of `/api/v3/user/{id}` are grouped together. Because of how `swagger-inline` works it meant I had to move the functions themselves inside `UserController.js` — I looked for a way to apply weights to the definitions but they don't seem to exist. Anyway, it doesn't affect the DX at all IMO, but scanning docs makes a little more sense.
Comparing to …
> HID-2060: v3 user methods

- README.md
> Correct link to docs in README

- api/controllers/TOTPController.js
- config/routes.js
- docs/v3/hid.yml
- docs/v3/swaggerBase.yaml
~⚠️ This PR depends on #106 — please review and merge it before this one ⚠️~
Documenting all the 2FA/TOTP endpoints.
> HID-2060: v3 TOTP endpoints

- api/controllers/ClientController.js
- api/controllers/TOTPController.js
- config/routes.js
- docs/v3/hid.yml
- docs/v3/swaggerBase.yaml
~⚠️  This PR depends on #107 — merge that before reviewing to reduce diff ⚠️~
Documenting v3 endpoints for OAuth clients.
> HID-2060: v3 client endpoints

- api/controllers/ViewController.js
- templates/register.html
Copy changes on the OAuth registration page.
> HID-2087: change title and remove subtitle from registration

- templates/footer.ejs
removing some stuff from the footer
> HID-2089: remove some elements from footer

- api/controllers/TOTPController.js
- config/routes.js
- docs/v3/hid.yml
Cloning the old v2 TOTP config function and making a fresh v3 version. The internals aren't radically different, but the output is a breaking change so it seemed easiest to copy the function instead of branching with a conditional like we do in other places.
> HID-2073: new v3 endpoint for TOTP config

- emails/post_register/fr/html.ejs
- emails/post_register/fr/subject.ejs
- emails/post_register/html.ejs
- emails/post_register/subject.ejs
- emails/register/fr/html.ejs
- emails/register/html.ejs
Updating emails for registration/post-registration on HID Auth. Any advice on FR appreciated, but otherwise we'll be testing on dev with Mailhog before sending to prod.
> HID-2088: register/post-register notifications

- api/controllers/UserController.js
Trying this again because #121 didn't capture all the places where this happens, including the one I've identified as problematic on our dev env.
> HID-2092: more DB error logs during email verification

- api/controllers/UserController.js
followup to eliminate some errors we saw on dev
> OPS-6812: prevent internal error when saving users

- config/logs.js
Just in case this is breaking ELK
> OPS-6812: restore the at-timestamp part of the log

- config/logs.js
Bonus: the comment above the affected line of code is now accurate :)
> OPS-6812: TIL the difference between clone and cloneDeep

- api/services/HelperService.js
> OPS-6839: update authorizedDomains list for dev to facilitate debugging

- api/controllers/ClientController.js
- config/logs.js
doing a lot more cleanup after we finally had logs appearing in Kibana
> HID-2110: cleanup

- config/logs.js
> HID-2110: cleanup v2

- docs/specs.yaml
> HID-2124: point API docs toward staging

- api/controllers/AuthController.js
- config/logs.js
Was taking another look at this in Kibana and found more stuff to fix. Same as previous PR #153 this will go to dev for testing within Kibana. I did test pretty extensively on my local to make sure there's no crashiness.
> OPS-6803: more log improvements

- api/controllers/AuthController.js
- emails/decommission_profile/fr/html.ejs
- emails/decommission_profile/html.ejs
Updating email templates in order to remind profile users that HDI Contacts is going away. We'll merge and test in dev using Jenkins. My local was able to produce en/fr just fine in small quantities.
> HID-2114: update decommissioning emails to profile users

- api/services/EmailService.js
> [OPS-7125] only append auth credentials when they exist

- assets/css/cd-card.css
- assets/css/cd-grid.css
- assets/css/page.css
- assets/css/profile-show.css
- templates/profile-edit.html
- templates/profile-show.html
Details on [HID-2154](https://humanitarian.atlassian.net/browse/HID-2154)
There may be more work needed to make this consistent with the Profile Edit page. And keeping, ditching or reducing the cd-grid component is up for discussion (based on whether it's useful elsewhere)
> HID-2154 profile cards

- api/controllers/ViewController.js
- assets/css/cd-alert.css
- assets/css/page.css
- templates/alert.html
- templates/register.html
~~This branch merges off https://github.com/UN-OCHA/hid_api/pull/175~~
It consists of implementing the most recent cd-alert component
https://github.com/UN-OCHA/common_design/tree/cd-226-design-system/components/cd-alert
https://feature.commondesign-unocha-org.ahconu.org/demo#cd-alert
> HID-2155 alerts

- assets/css/page.css
- templates/settings-password.html
No ticket, I just wanted to take care of some small-ish tweaks to forms that @left23 and I had discussed while pairing on stuff.
Review not needed so urgently, just tagged you FYI.
> Form tweaks

- api/services/HelperService.js
Just one step of the process. Not urgent, does not need to be in sync with a particular deploy.
> HID-2152: remove outdated/legacy domains from allow-list

- api/controllers/UserController.js
- config/env/development.js
- config/env/local.js
- config/env/production.js
- config/env/staging.js
- config/env/testing.js
- config/logs.js
- package-lock.json
- package.json
Winston 3 had some breaking changes and as a result we had to [refactor the log rewriter into the new thing called a formatter](https://github.com/winstonjs/winston/blob/master/UPGRADE-3.0.md#migrating-filters-and-rewriters-to-formats-in-winston3). What came with the breaking change is the inconvenience that formatters continually mutate the same object as it gets passed along, which was incompatible with our old formatter, which was sanitizing important data before writing the log (e.g. client secrets, specific payload fields like passwords, etc)
Most of the changes are find/replace inside the formatter itself, since the mutations were required to happen on the `info` that gets passed in, but we didn't want those changes affecting the `request` object when it gets used again after being …
> HID-2024: winston@3 upgrade

- package-lock.json
- package.json
- templates/totp.html
Only one form was missing the attribute and it's fixed now.
> HID-2132: allow password managers to autocomplete TOTPs

- api/controllers/AuthController.js
- api/controllers/UserController.js
- docs/swaggerBase.yaml
- package-lock.json
- package.json
restoring the following props to `account.json`
- `family_name`
- `given_name`
- `user_id`
> HID-2208: restore family_name, given_name, user_id

- api/controllers/AuthController.js
- api/controllers/UserController.js
- docs/swaggerBase.yaml
- package-lock.json
- package.json
- HID-2208: restore `family_name`, `given_name`, `user_id`
> Production followup 2021-03-18

- CONTRIBUTING.md
- README.md
I accidentally branched of of HID-2213. That was unintentional. My apologies! Anyway, once #239 is closed this diff will rebase to dev but I kept the original branch base so that this PR can be reviewed more easily.
Housekeeping PR to scrub the docs of old references and links.
> HID-2214: update docs

- api/controllers/ViewController.js
- api/models/Client.js
- api/models/User.js
- package-lock.json
- package.json
This takes care of a couple bugs all related to writing data to a User record. We had seemingly unrelated problems that all ended up being similar once enough data had been collected: trying to update a user with no changes.
So the updates to User.js cover that part. Basically there was a fatal error. You can reproduce by editing your profile and then immediately saving using the "Update Name" button. Having this branch checked out should prevent the error, and it will report having saved your un-edited profile like you'd expect.
The second half stemmed from yet another instance where the `User.authorizedClients` array wasn't getting populated, and additionally we wanted some specially-formatted version of the data on one URL. Instead of manually building it for that page, I moved the …
> HID-2225: User and Client model population

- api/services/HelperService.js
- docs/swaggerBase.yaml
- package-lock.json
- package.json
> OPS-7225: disaster recovery domains

- .dockerignore
- .gitignore
- api/controllers/UserController.js
- api/services/HelperService.js
- config/env/index.js
- docs/swaggerBase.yaml
- package-lock.json
- package.json
Moving our hardcoded domains to an environment variable.
> no more hardcoded authorizedDomains! yey!

- commands/__swaggerVersion.js
- commands/createDummyClient.js
- commands/createDummyUser.js
- commands/createOAuthClient.js
- commands/deleteExpiredTokens.js
- commands/deleteExpiredUsers.js
- commands/forceResetPassword.js
- commands/forceResetPasswordAlert.js
- commands/forceResetPasswordAlert7.js
- commands/migrateRedirectUrls.js
- commands/sendSpecialPasswordResetEmail.js
Changes were made to environment in #261 but usage was not updated in
commands. This commit makes that update.
cc @teodorescuserban @rupl
> fix environment use in commands

- api/controllers/AuthController.js
The actual issue in the ticket isn't resolved, but I thought I'd slide this in before leaving for holiday.
> HID-2230: typo in user-facing message

- CHANGELOG.md
- package-lock.json
- package.json
Look at that beautiful changelog!
> chore(release): 5.0.0

- CHANGELOG.md
- package-lock.json
- package.json
Preparing the Prod release for 2 Dec 2021.
> Production 2021-12-02

- api/policies/AuthPolicy.js
- api/services/EmailService.js
- commands/deleteExpiredUsers.js
- emails/admin_delete/fr/html.ejs
- emails/admin_delete/html.ejs
- emails/auto_expire/fr/html.ejs
- emails/auto_expire/fr/subject.ejs
- emails/auto_expire/html.ejs
- emails/auto_expire/subject.ejs
We missed one email in HID-2305 and are adding a new one to differentiate between two types of account deletion:
1. `auto_expire`: Daily purges of DB by Jenkins, which targets new registrations that fail to verify the email within 7 days.
2. `admin_delete`: Individual account deletions by an admin
Type 1: register a new account, then without clicking the link in mailhog, open up `commands/deleteExpiresUsers.js` and change the query it runs (you can skip this part if you want to wait 7 days before completing review 😁 )
```diff
diff --git commands/deleteExpiredUsers.js commands/deleteExpiredUsers.js
index 9a54dbef..47bc378e 100644
--- commands/deleteExpiredUsers.js
+++ commands/deleteExpiredUsers.js
@@ -14,14 +14,14 @@ const EmailService = require('../api/services/EmailService');
async …
```
> HID-2316: update more emails

- api/models/User.js
Docs only! we had a ticket to delete this stuff and only after digging in I realized it's still used. New docs to explain it to future someone.
> HID-2290: explain the User.expires property in the model

- CHANGELOG.md
- docs/swaggerBase.yaml
- package-lock.json
- package.json
Some final security updates, plus the new release notes for the upcoming deployment.
> Production 2022-01-27

- CHANGELOG.md
- package-lock.json
- package.json
> HID-2337: prepare release for 2022-02-24

- CONTRIBUTING.md
Trying to get ahead of the game here 😁  — hopefully this can smooth out the HID stuff using SNAP experiences.
No functional change to codebase. Docs only.
> [HID-2344] standard docs for creating Releases

- CHANGELOG.md
- package-lock.json
- package.json
> Production deploy 2022-07-14

- CHANGELOG.md
- package-lock.json
- package.json
Prepping today's STAGE release.
> Production 2022-08-11

- .github/workflows/build.yml
- .travis.yml
- README.md
Maybe this PR will try to build and we see if it works?
> [OPS-8546] Remove flowdock notifications and replace with Slack

- templates/includes/header.ejs
> [HID-2354] update tracking code to use GTM/GA4

- config/web.js
Refs: HID-2354, https://github.com/UN-OCHA/hid-api/pull/383
> fix: allow new GTM inline script

- CHANGELOG.md
- docs/swaggerBase.yaml
- package-lock.json
- package.json
> chore(release): 5.1.9

- CHANGELOG.md
- package-lock.json
- package.json
Prepping regularly scheduled release.
> chore(release): 5.2.0

- .eslintrc.js
- .github/workflows/checks.yml
> chore(ci): slack notifications for PR checks

- CHANGELOG.md
- package-lock.json
- package.json
> chore(release): 5.2.2

- Dockerfile
- docker-compose.example.yml
- package.json
- server.js
Refs: HID-2382
Apparently the case matters for auto-building branches.
> chore: attempting to upgrade node.js

- CHANGELOG.md
- config/web.js
- docs/swaggerBase.yaml
- package-lock.json
- package.json
We really needed an update to the Hapi ecosystem. There are a few stragglers but this takes care of most of them. I'm testing this by deploying the branch onto dev so there's no reviewer assigned.
> [HID-2383] update deps

- package-lock.json
Results of running `npm audit fix`
> chore(security): dependency updates

- .eslintrc.js
- .github/workflows/checks.yml
- _tests/unit/numbers.test.js
- _tests/unit/session.test.js
- api/controllers/AdminController.js
- api/controllers/ViewController.js
- api/policies/AuthPolicy.js
- config/routes.js
- config/web.js
- index.js
- plugins/hapi-auth-api/README.md
- plugins/hapi-auth-api/index.js
- plugins/hapi-auth-session/README.md
- plugins/hapi-auth-session/index.js
- server.js
Replaces the boilerplate conditionals in each route handler with an authentication strategy specified on each route. The ticket has more details as to why I wrote a custom plugin. TL;DR we have technical/business reasons to hold onto `yar` so the custom plugin was the smallest change that leverages the existing codebase.
End result in the controllers is that the `cookie` is guaranteed to exist by the time the route handler is executing. We no longer need all the conditionals and redirects that used to be at the top of every route handler.
> [HID-2389] DRY session auth

- CHANGELOG.md
- docs/swaggerBase.yaml
- package-lock.json
- package.json
- **security:** update node.js deps ([cf0f585](https://github.com/UN-OCHA/hid-api/pull/431/commits/cf0f585cb43cc97f388ffbb4d7b9680a760f5d40))
> Release 2024-04-18

- CHANGELOG.md
- docs/swaggerBase.yaml
- package-lock.json
- package.json
> Release 2024 06 13

- CHANGELOG.md
- docs/swaggerBase.yaml
- package-lock.json
- package.json
HID-2417
Regular package updates only.
> Release 2024 07 11

- CHANGELOG.md
- docs/swaggerBase.yaml
- package-lock.json
- package.json
[HID-2420](https://humanitarian.atlassian.net/browse/HID-2420)
Regular package updates only.
[HID-2420]: https://humanitarian.atlassian.net/browse/HID-2420?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(release): 5.3.10

- CHANGELOG.md
- docs/swaggerBase.yaml
- package-lock.json
- package.json
Regular release - NPM audit and version bump.
> chore(release): 5.3.11

- CHANGELOG.md
- docs/swaggerBase.yaml
- package-lock.json
- package.json
Regular security updates
* chore(release): 5.3.11 by @lazysoundsystem in https://github.com/UN-OCHA/hid-api/pull/444
**Full Changelog**: https://github.com/UN-OCHA/hid-api/compare/v5.3.10...v5.3.11
> Production 2024-09-05

- .github/workflows/checks.yml
> chore: Bump actions to avoid breakage.

- CHANGELOG.md
- docs/swaggerBase.yaml
- package-lock.json
- package.json
- **chore(release): 5.3.15**
- **chore(release): 5.3.16**
> HID 2425 production deploy 2025 02 20

- CHANGELOG.md
- docs/swaggerBase.yaml
- package-lock.json
- package.json
- **updates: npm audit fixes**
- **chore(release): 5.3.18**
> HID 2430 monthly deployment

- api/controllers/ViewController.js
This way we avoid a potential XSS, which I must say I am not able to reproduce. HID tells me to go awya when I try to inject some script intp the email field. Still, better safe than sorry.
Refs: HID-2436
> fix(security): Do not echo the entered value back to the user.
